// https://lucide.dev/icons/
// Country icons: https://www.svgrepo.com/collection/countrys-flags/
// LinkedIn/Facebook/Twitter: https://icons8.com/icons/

import {
  AlertTriangle,
  Loader,
  LoaderCircle,
  LoaderCircleIcon,
  Calendar,
  HomeIcon,
  LogOut,
  Mail,
  Shield,
  User,
  EyeIcon,
  EyeOffIcon,
  BadgeCheck,
  Bell,
  GalleryVerticalEnd,
  Book,
  Building,
  ChevronRight,
  ChevronLeft,
  Handshake,
  ShieldUser,
  Check,
  ChartNoAxesColumnDecreasing,
  Search,
  BookOpen,
  MapPin,
} from 'lucide-react';

export const Icons = {
  alertTriangle: AlertTriangle,
  calender: Calendar,
  home: HomeIcon,
  logout: LogOut,
  mail: Mail,
  shield: Shield,
  user: User,
  loader: Loader,
  loaderCircle: LoaderCircle,
  loaderCircleIcon: LoaderCircleIcon,
  eye: EyeIcon,
  eyeOff: EyeOffIcon,
  badgeCheck: BadgeCheck,
  bell: Bell,
  galleryVerticalEnd: GalleryVerticalEnd,
  book: Book,
  building: Building,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  handshake: Handshake,
  shieldUser: ShieldUser,
  check: Check,
  chartNoAxesColumnDecreasing: ChartNoAxesColumnDecreasing,
  search: Search,
  bookOpen: BookOpen,
  mapPin: MapPin,
};
